# Generated by Django 6.0.7 on 2026-07-27 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('total_miles_driving', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grid_segments', models.JSONField(default=list)),
                ('totals', models.JSONField(default=dict)),
                ('remarks', models.JSONField(default=list)),
                ('recap', models.JSONField(default=dict)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['log_date'],
                'unique_together': {('trip', 'log_date')},
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (not driving)')], max_length=3)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('is_34h_restart_segment', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='drivers.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='trips.trip')),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['driver', 'start_at'], name='log_driver_start_idx'), models.Index(fields=['driver', 'end_at'], name='log_driver_end_idx'), models.Index(fields=['trip', 'start_at'], name='log_trip_start_idx'), models.Index(fields=['driver', 'status', 'start_at'], name='log_driver_status_start_idx')],
            },
        ),
    ]
