# Generated by Django 6.0.7 on 2026-07-27 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='Demo Driver', max_length=120)),
                ('home_terminal_tz', models.CharField(default='America/Chicago', max_length=64)),
                ('cycle_type', models.CharField(choices=[('70_8', '70-hour / 8-day')], default='70_8', max_length=8)),
                ('current_cycle_used_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_34h_restart_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
