# Generated by Django 6.0.7 on 2026-07-27 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('ready', 'Ready'), ('failed', 'Failed')], default='planning', max_length=16)),
                ('current_address', models.CharField(max_length=255)),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('current_cycle_used_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('adverse_conditions', models.BooleanField(default=False)),
                ('auto_34h_restart', models.BooleanField(default=True)),
                ('trip_start_at', models.DateTimeField()),
                ('home_terminal_tz', models.CharField(default='America/Chicago', max_length=64)),
                ('route_geometry', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('approximate_routing', models.BooleanField(default=False)),
                ('pdf_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='skipped', max_length=16)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='trip_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('origin', 'Origin'), ('pickup', 'Pickup'), ('fuel', 'Fuel'), ('rest', 'Rest'), ('dropoff', 'Dropoff')], max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('arrive_at', models.DateTimeField()),
                ('depart_at', models.DateTimeField()),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence', 'arrive_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['created_at'], name='trips_trip_created_b7c7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'created_at'], name='trips_trip_driver__7ad02c_idx'),
        ),
        migrations.AddIndex(
            model_name='tripstop',
            index=models.Index(fields=['trip', 'sequence'], name='trips_trips_trip_id_54bb53_idx'),
        ),
    ]
